---
- name: Collect facts from all devices in the Ansible Inventory 
  hosts: all
  gather_facts: true
  gather_subset: min
  connection: network_cli
  ignore_errors: true

- name: Collect ACI software version and query Cisco PSIRT OpenVuln API
  hosts: localhost
  gather_facts: false
  gather_subset: min
  vars:
#    aci:
#      - { apic: <APIC-URL/IP>, aci_user: <username>, aci_pass: <password> }
    host_list: # Needs at least an empty tag: and host: variable per list item #
      - { name: nxos, version: 7.0(3)I7(7), tag: Test_NXOS, host: N9K-1 }
      - { name: aci, version: 14.2(5k), tag: Test_ACI, host: ACI-leaf-1 }
    client_key: <Provided via Cisco API console>
    client_secret: <Provided via Cisco API console>
    slack_token: <Provided via custom slack app - incoming webhooks>
    known_vuln: [] # Empty default list in case known_vuln.yml not found

  tasks:

    - name: INCLUDE KNOWN VULN FILE
      include_vars:
        file: known_vuln.yml
        name: known_vuln
      ignore_errors: yes # In case the file doesn't exist #

    - name: Query ACI fabric nodes
      aci_rest:
        host: "{{ item.apic }}"
        username: "{{ item.aci_user }}"
        password: "{{ item.aci_pass }}"
        validate_certs: false
        method: get
        path: /api/node/class/firmwareRunning.json
      loop: "{{ aci }}"
      register: aci_firmware
      when: aci is defined

    # Complete the host_list with ACI, NX-OS, IOS-XE and IOS devices #

    - name: ADD ACI DEVICES TO HOST LIST
      set_fact:
        host_list: "{{ host_list | default ([]) + [{ 'name': 'aci', 'version': '1' + item.1.firmwareRunning.attributes.peVer, 'tag': item.0.item.apic, 'host': item.1.firmwareRunning.attributes.dn.split('/')[2] }] }}"
      loop: "{{ aci_firmware.results | default ([]) | subelements('imdata') }}" # Definitely needs an empty list in case aci variable is not defined! #
      loop_control:
        label: "{{ item.0.item.apic }} {{ item.1.firmwareRunning.attributes.dn.split('/')[2] }}"
      when: aci is defined

    - name: ADD NX-OS DEVICES TO HOST LIST
      set_fact:
        host_list: "{{ host_list | default ([]) + [{ 'name': 'nxos', 'version': hostvars[item].ansible_facts.net_version, 'tag': hostvars[item].group_names | join(' '), 'host': hostvars[item].ansible_facts.net_hostname }] }}"
      loop: "{{ groups['all'] }}"
      when:
        - hostvars[item].ansible_network_os is defined
        - hostvars[item].ansible_network_os == "nxos"

    - name: ADD IOS-XE DEVICES TO HOST LIST
      set_fact:
        host_list: "{{ host_list | default ([]) + [{ 'name': 'iosxe', 'version': hostvars[item].ansible_facts.net_version, 'tag': hostvars[item].group_names | join(' '), 'host': hostvars[item].ansible_facts.net_hostname }] }}"
      loop: "{{ groups['all'] }}"
      when:
        - hostvars[item].ansible_network_os is defined
        - hostvars[item].ansible_network_os == "ios"
        - hostvars[item].ansible_facts.net_version is defined
        - hostvars[item].ansible_facts.net_version.split('.') | first in  ['03', '16', '17']

    - name: ADD IOS DEVICES TO HOST LIST
      set_fact:
        host_list: "{{ host_list | default ([]) + [{ 'name': 'ios', 'version': hostvars[item].ansible_facts.net_version, 'tag': hostvars[item].group_names | join(' '), 'host': hostvars[item].ansible_facts.net_hostname }] }}"
      loop: "{{ groups['all'] }}"
      when:
        - hostvars[item].ansible_network_os is defined
        - hostvars[item].ansible_network_os == "ios"
        - hostvars[item].ansible_facts.net_version is defined
        - hostvars[item].ansible_facts.net_version.split('.') | first in ['12', '15']

    # Query the Cisco PSIRT openVuln API

    - name: CISCO OPENVULN API LOGIN
      uri:
        url: https://cloudsso.cisco.com/as/token.oauth2
        headers:
          Content-Type: application/x-www-form-urlencoded
        method: POST
        body:
          grant_type: client_credentials
          client_id: "{{ client_key }}"
          client_secret: "{{ client_secret }}"
        validate_certs: no
        body_format: form-urlencoded
#      environment:
#        https_proxy: http://<proxy-url>:<port>
      register: login

    - name: GET CISCO PSIRT OPEN VULN
      uri:
        url: https://api.cisco.com/security/advisories/{{ item.name }}?version={{ item.version }}
        headers:
          Accept: application/json
          Authorization: "{{ login.json.token_type }} {{ login.json.access_token }}"
        method: GET
        validate_certs: no
        status_code: [200, 406] # API reports 406 NO_DATA if no matching adv is found #
      loop: "{{ host_list | unique(attribute='version') | sort(attribute='version') | sort(attribute='name') }}"
#      environment:
#        https_proxy: http://<proxy-url>:<port>
      register: open_vuln

     # Process API response #

    - name: TEMPLATE OUT MARKDOWN REPORT
      template:
        src: openvuln.j2
        dest: openvuln.md

    - name: TEMPLATE OUT CSV REPORT
      template:
        src: openvuln_csv.j2
        dest: openvuln.csv

#    - name: SEND NOTIFICATION VIA SLACK
#      slack:
#        token: "{{ slack_token }}"
#        msg: "{{ item.0.item.name | upper }} {{ item.0.item.version }} has new advisory <{{ item.1.publicationUrl }}|{{ item.1.advisoryId }}> with `CVSS {{ item.1.cvssBaseScore }}`"
#      loop: "{{ open_vuln.results | default([]) | subelements('json.advisories', skip_missing=True) }}"
#      loop_control:
#        label: "Send message for {{ item.0.item.name | upper }} {{ item.0.item.version }} {{ item.1.advisoryId }}"
#      when: item.1.advisoryId not in known_vuln
